### ISSUE TITLE
BeautifulSoup(response.text, 'xml').projects return None

### ISSUE THREAD

**Issue by swdream** [bogdal/sentry-youtrack#17]
When selecting the YouTrack tab of a project, I got this error:
```
 Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!
If you're daring, you may want to try the following:
Give it a few seconds and reload the page.
If all else fails, create an issue with more details.
```
I checked log and saw:
```
sentry[14332] ERROR django.request base.handle_uncaught_exception:224 Internal Server Error: /team/project/settings/plugins/youtrack/
    Traceback (most recent call last):
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/../django/core/handlers/base.py", line 112, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/../django/views/generic/base.py", line 69, in view
        return self.dispatch(request, *args, **kwargs)
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 29, in _wrapper
        return bound_func(*args, **kwargs)
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 99, in _wrapped_view
        response = view_func(request, *args, **kwargs)
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/../django/utils/decorators.py", line 25, in bound_func
        return func(self, *args2, **kwargs2)
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 172, in dispatch
        return self.handle(request, *args, **kwargs)
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/web/frontend/project_plugin_configure.py", line 22, in handle
        view = plugin.configure(request, project=project)
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/plugins/base/v1.py", line 472, in configure
        return default_plugin_config(self, project, request)
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/plugins/base/configuration.py", line 37, in default_plugin_config
        prefix=plugin_key,
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/../sentry_youtrack/forms.py", line 194, in __init__
        for project in client.get_projects():
      File "/usr/local/sentry/local/lib/python2.7/site-packages/sentry/../sentry_youtrack/youtrack.py", line 157, in get_projects
        for project in BeautifulSoup(response.text, 'xml').projects:
    TypeError: 'NoneType' object is not iterable
```
sentry version: 8.4.0
sentry-youtrack plugin version: 0.3.1
YouTrack version: youtrack-6.5.17105
beautifulsoup4: 4.5.1

thanks & best regards.

**Comment by swdream** [comment]
it is because I configured URL wrongly in the first time.
thanks

**Comment by swdream** [comment]
@bogdal how can I re-configure youtrack url for a sentry project?

**Comment by bogdal** [comment]
You can change the youtrack url on the configuration plugin page (assuming that you are able to open this page).

**Comment by swdream** [comment]
@bogdal No, if the wrong youtrack url is configured in the first time, we are not able to open the youtrack plugin configuration page. So we cannot change/update youtrack url

**Comment by bogdal** [comment]
@swdream Error handling is definitely something to fix.

**Comment by swdream** [comment]
@bogdal I created a new issue which is clearer
https://github.com/bogdal/sentry-youtrack/issues/18
so you can close this issue.
Thank you very much for your help

**Comment by bogdal** [comment]
:+1:
