### ISSUE TITLE
Cannot integrate with youtrack

### ISSUE THREAD

**Issue by systemfreund** [bogdal/sentry-youtrack#9]
I'm getting the error below when I try to use sentry-youtrack.
Sentry version: 7.5.4
Youtrack version: 6.0
```
[ERROR] Internal Server Error: /myorganization/myproject/group/2429/actions/youtrack/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 236, in wrapped
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/decorators.py", line 182, in _wrapped
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/groups.py", line 534, in group_plugin_action
    response = plugin.get_view_response(request, group)
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_youtrack/plugin.py", line 121, in get_view_response
    return self.view(request, group)
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_youtrack/plugin.py", line 141, in view
    return view(request, group, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_youtrack/plugin.py", line 173, in project_issues_view
    yt_client = self.get_youtrack_client(group.project)
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_youtrack/plugin.py", line 49, in get_youtrack_client
    return YouTrackClient(**settings)
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_youtrack/youtrack.py", line 27, in __init__
    self._login(username, password)
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_youtrack/youtrack.py", line 38, in _login
    self._request(url, data=credentials, method='post')
  File "/usr/local/lib/python2.7/site-packages/sentry/../sentry_youtrack/youtrack.py", line 57, in _request
    self.response = requests.post(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 447, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 378, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 303, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 360, in prepare_url
    "Perhaps you meant http://{0}?".format(url))
MissingSchema: Invalid URL u'/rest/user/login': No schema supplied. Perhaps you meant http:///rest/user/login?
Discarded invalid value for interface: sentry.interfaces.Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/coreapi.py", line 355, in validate_data
    inst = interface.to_python(value)
  File "/usr/local/lib/python2.7/site-packages/sentry/interfaces/exception.py", line 176, in to_python
    for v in data['values']
  File "/usr/local/lib/python2.7/site-packages/sentry/interfaces/exception.py", line 47, in to_python
    stacktrace = Stacktrace.to_python(data['stacktrace'])
  File "/usr/local/lib/python2.7/site-packages/sentry/interfaces/stacktrace.py", line 438, in to_python
    assert data.get('frames')
AssertionError
Discarded invalid value for interface: sentry.interfaces.Exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/coreapi.py", line 355, in validate_data
    inst = interface.to_python(value)
  File "/usr/local/lib/python2.7/site-packages/sentry/interfaces/exception.py", line 176, in to_python
    for v in data['values']
  File "/usr/local/lib/python2.7/site-packages/sentry/interfaces/exception.py", line 47, in to_python
    stacktrace = Stacktrace.to_python(data['stacktrace'])
  File "/usr/local/lib/python2.7/site-packages/sentry/interfaces/stacktrace.py", line 438, in to_python
    assert data.get('frames')
AssertionError
```

**Comment by alexandrul** [comment]
I couldn't locate the error message yet, but attempting to save the credentials in the "YouTrack Configuration" tab has no visible result.

Sentry 7.7.0
YouTrack 6.0 build 12634

**Comment by bogdal** [comment]
The new version `0.2.4` is compatible with the latest sentry. It's available on pypi. Check it out.
